"""add specialist role and person_id to users

Revision ID: 09036271a8a9
Revises: 07e8c58dc02e
Create Date: 2026-08-31 13:41:44.766892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09036271a8a9'
down_revision: Union[str, Sequence[str], None] = '07e8c58dc02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_id', sa.String(length=36), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('CLIENT', 'STAFF'),
               type_=sa.Enum('CLIENT', 'STAFF', 'SPECIALIST', name='user_role'),
               existing_nullable=False)
    op.create_foreign_key('fk_users_person_id', 'users', 'people', ['person_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_users_person_id', 'users', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_person_id', 'users', type_='foreignkey')
    op.drop_index('ix_users_person_id', table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CLIENT', 'STAFF', 'SPECIALIST', name='user_role'),
               type_=mysql.ENUM('CLIENT', 'STAFF'),
               existing_nullable=False)
    op.drop_column('users', 'person_id')
    # ### end Alembic commands ###
